# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxMessage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'
  # Pods for RxMessage

end
