# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


def shared_pods
  pod 'SnapKit'
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'Starscream'
  pod 'RealmSwift'
end


target 'RxMessage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  shared_pods

  # Pods for RxMessage
end

target 'RxMessageTests' do
  use_frameworks!
  shared_pods
  pod 'RxTest'
  pod 'RxBlocking'
  
end


